site_name: Ligolo-ng Documentation
site_url: https://docs.ligolo.ng
repo_url: https://github.com/nicocha30/ligolo-ng
repo_name: nicocha30/ligolo-ng
theme:
  features:
    - navigation.tabs
  name: material
  palette:
    scheme: slate
    primary: black
  logo: assets/ligolo.svg
nav:
  - Getting Started:
      - Introduction: index.md
      - Installing and Building: InstallBuild.md
      - Quickstart: Quickstart.md
      - Configuration File: Config-File.md
      - Listeners : Listeners.md
      - Agent as server (Bind Connection) : Bind.md
      - Access to agent's local ports (127.0.0.1): Localhost.md
      - Using the Web Interface: webui.md

  - Sample and Advanced Usage:
      - Basic Tunneling: sample/basic.md
      - Advanced Pivoting: sample/double.md
      - Running behind a reverse proxy: sample/Configuring-a-reverse-proxy.md
      - (WIP) Creating a Ligolo-ng router: sample/router.md
      - (WIP) Ligolo-baremetal: sample/baremetal.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
